version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
	  command: pip install django-tinymce4-lite
          command: ./manage.py test --settings=mysite.settings.dev
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
