# Generated by Django 2.2.16 on 2020-09-23 09:59

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
