# Generated by Django 2.2.16 on 2020-09-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
