# Generated by Django 2.2.16 on 2020-09-23 13:07

from django.db import migrations
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_quill_post_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=quilljs.fields.RichTextField(),
        ),
    ]
