# Generated by Django 2.2.16 on 2020-09-23 13:11

from django.db import migrations
import editorjs_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_quill_post_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=editorjs_field.fields.EditorJSField(),
        ),
    ]
