# Generated by Django 2.2.16 on 2020-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
