# Generated by Django 2.2.16 on 2020-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200927_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
